source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'SwiftPlayer_Example' do
  pod 'SwiftPlayer', :path => '../'
  pod 'ObjectMapper'
  pod 'AlamofireImage'
end

target 'SwiftPlayer_Tests' do
  pod 'SwiftPlayer', :path => '../'
end
